---
- hosts: all
  become: yes
  
  tasks:
  - name: Deleting the users.
    user:
      name: "{{ item }}"
      state: absent
      remove: yes
      force: yes
    with_items:
      - test1
      - test2
